# Generated by Django 6.0.5 on 2026-06-30 07:24

from django.db import migrations


def seed_courses(apps, schema_editor):
    Course = apps.get_model('core', 'Course')
    courses = [
        ('AMH-KIDS', 'Amharic for kids', 450.00),
        ('GEEZ-YTH', 'Geez for youth', 500.00),
        ('GRAPHIC-DS', 'Graphic design', 600.00),
        ('FE-BE', 'Frontend and backend together what freelancers make people pay', 500.00),
        ('FRONT-END', 'Front-End', 625.00),
        ('BACKEND', 'Backend', 725.00),
    ]
    for course_id, course_name, rate in courses:
        Course.objects.get_or_create(
            course_id=course_id,
            defaults={'course_name': course_name, 'rate': rate},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_tutor_courses'),
    ]

    operations = [
        migrations.RunPython(seed_courses, migrations.RunPython.noop),
    ]
